In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.cluster import KMeans

In [140]:
df = pd.read_csv("Mall_Customers.csv")

In [141]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [142]:
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [143]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [144]:
df.duplicated().sum()
df = df.drop_duplicates()

In [145]:
df.columns = df.columns.str.strip()

In [146]:
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})

In [147]:
# X = df[['Age','Gender','Annual Income (k$)', 'Spending Score (1-100)']]

In [148]:
X = df[['Spending Score (1-100)']]

In [149]:
kmeans = KMeans(n_clusters=4, random_state=42)

In [150]:
df['Cluster'] = kmeans.fit_predict(X)

In [151]:
# plt.plot(range(1, 11), wcss)
# plt.xlabel("Number of Clusters")
# plt.ylabel("WCSS")
# plt.title("Elbow Method")
# plt.show()

In [152]:
df.head()

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Cluster
0,1,0,19,15,39,2
1,2,0,21,15,81,1
2,3,1,20,16,6,3
3,4,1,23,16,77,1
4,5,1,31,17,40,2

In [153]:
df['Cluster'].value_counts()

Cluster
0    63
1    57
2    41
3    39
Name: count, dtype: int64

In [154]:
from sklearn.metrics import silhouette_score

score = silhouette_score(X, df['Cluster'])

print("Silhouette Score:", score)

Silhouette Score: 0.6012604522879379

In [155]:
# 0 high paying
# 1 average
# 3 below average
# 2 lowest

In [156]:
import joblib

joblib.dump(kmeans, "kmeans_model.pkl")

['kmeans_model.pkl']