In [2]:
import numpy as np 
import pandas as pd  
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("stock_data.csv")

In [4]:
df.head()

   Unnamed: 0     Stock_1     Stock_2    Stock_3     Stock_4     Stock_5
0  2020-01-01  101.764052  100.160928  99.494642   99.909756  101.761266
1  2020-01-02  102.171269   99.969968  98.682973  100.640755  102.528643
2  2020-01-03  103.171258   99.575237  98.182139  100.574847  101.887811
3  2020-01-04  105.483215   99.308641  97.149381  100.925017  101.490049
4  2020-01-05  107.453175   98.188428  99.575396  101.594411  101.604283

In [5]:
df = df.drop("Unnamed: 0", axis=1)

print(df.head())

      Stock_1     Stock_2    Stock_3     Stock_4     Stock_5
0  101.764052  100.160928  99.494642   99.909756  101.761266
1  102.171269   99.969968  98.682973  100.640755  102.528643
2  103.171258   99.575237  98.182139  100.574847  101.887811
3  105.483215   99.308641  97.149381  100.925017  101.490049
4  107.453175   98.188428  99.575396  101.594411  101.604283

In [6]:
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Stock_1  365 non-null    float64
 1   Stock_2  365 non-null    float64
 2   Stock_3  365 non-null    float64
 3   Stock_4  365 non-null    float64
 4   Stock_5  365 non-null    float64
dtypes: float64(5)
memory usage: 14.4 KB

          Stock_1     Stock_2     Stock_3     Stock_4     Stock_5
count  365.000000  365.000000  365.000000  365.000000  365.000000
mean   107.772577   81.105216   94.519502  117.407560  106.866865
std      7.398296   11.435212    6.519213    6.778527    3.760968
min     91.474442   62.414219   81.111434   99.909756   99.833309
25%    101.603117   69.328263   89.788068  112.209912  103.927072
50%    107.421299   84.283525   94.495546  117.788079  106.411328
75%    113.741728   91.548859   99.919465  123.132365  109.178007
max    121.901773  100.160928  107.588373  129.911386  116.243803

In [7]:
df.isnull().sum()

Stock_1    0
Stock_2    0
Stock_3    0
Stock_4    0
Stock_5    0
dtype: int64

In [8]:
df.duplicated().sum()
df = df.drop_duplicates()

In [9]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [10]:
stock = "Stock_1"

X = df[[stock]]

Y = df[stock].shift(-1)

X = X[:-1]
Y = Y[:-1]

print("X sample:")
print(X.head())

print("\nY sample:")
print(Y.head())

X sample:
      Stock_1
0  101.764052
1  102.171269
2  103.171258
3  105.483215
4  107.453175

Y sample:
0    102.171269
1    103.171258
2    105.483215
3    107.453175
4    106.403059
Name: Stock_1, dtype: float64

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y,
    test_size=0.2,
    shuffle=False
)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

Train size: 291
Test size: 73

In [12]:
model = LinearRegression()

model.fit(X_train, Y_train)

print("Linear Regression Model Trained Successfully!")

Linear Regression Model Trained Successfully!

In [13]:
predictions = model.predict(X_test)

print("First 5 Predictions:")
print(predictions[:5])

First 5 Predictions:
[104.07010192 106.43098508 105.31973366 105.17872361 106.35632948]

In [14]:
mae = mean_absolute_error(Y_test, predictions)
rmse = np.sqrt(mean_squared_error(Y_test, predictions))

print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)

Mean Absolute Error (MAE): 0.7893569350043399
Root Mean Squared Error (RMSE): 0.9772939318022416

In [15]:
r2 = r2_score(Y_test, predictions)
print("R2 :  ",r2)

R2 :   0.9567323912570144

In [16]:
result = pd.DataFrame({
    "Today Price (X)": X_test[stock].values,
    "Actual Next Day Price (Y)": Y_test.values,
    "Predicted Next Day Price": predictions
})

print(result.head(10))

   Today Price (X)  Actual Next Day Price (Y)  Predicted Next Day Price
0       103.979595                 106.375198                104.070102
1       106.375198                 105.247604                106.430985
2       105.247604                 105.104521                105.319734
3       105.104521                 106.299445                105.178724
4       106.299445                 106.403326                106.356329
5       106.403326                 107.023608                106.458705
6       107.023608                 106.596103                107.069997
7       106.596103                 106.990568                106.648688
8       106.990568                 105.592708                107.037436
9       105.592708                 107.343573                105.659835